name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: 🚀 Test and build
    timeout-minutes: 15

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0

      - name: ❇️ Setup node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: pnpm

      - name: 📦 Cache ollama model
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.ollama
          key: ${{ runner.os }}-ollama

      - name: 📥 Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 🐳 Start the environment
        run: |
          docker compose up -d
          echo "🦙 Waiting ollama to be ready"
          until docker-compose exec 06_2_ia_good_practices_ollama echo "ready"; do sleep 5; done
          docker-compose exec 06_2_ia_good_practices_ollama ollama pull mistral

      - name: 🛠️ Build
        run: pnpm build

      - name: ✅ Test
        run: |
          pnpm test:ci
          pnpm test
